#!/usr/bin/env ruby
require 'rubygems'
require 'slugify'
require 'bundler/setup'
require_relative '../lib/helper_download'
require_relative '../lib/helper_extract'
require_relative '../lib/helper_selector'

class Selector2008
  include HelperSelector

  def initialize
    @sessions_filepath = Dir[File.expand_path('./data/2008/sessions*.html')]
    @authors_filepath = Dir[File.expand_path('./data/2008/authors/*.html')]
    @workshop_filepath = File.expand_path('./data/2008/workshop.html')
    @ressources_filepath = File.expand_path('./data/2008/ressources.html')
  end

  def clean_text(text)
    text.delete("\t").tr("\r", ' ').tr("\n", ' ').strip
  end

  def description(event)
    tags = element(event, '.description p')
    return nil if tags.length < 2
    desc = tags[1..-1].map(&:text).join(' ')
    clean_text(desc)
  end

  def authors(event)
    tags = element(event, '.description p')
    return nil if tags.length < 2
    links = element(tags, 'a')
    authors = []
    links.each do |link|
      next if link.attr('href') =~ /^mailto/
      authors << {
        name: link.text
      }
    end
    authors
  end

  def title(event)
    h3 = element(event, 'h3')
    element(h3, 'span,abbr').remove
    h3.text.delete("\t").tr("\n", ' ').split(':')[1..-1].join(':').strip
  end

  def sessions
    sessions = []
    @sessions_filepath.each do |filepath|
      doc = Nokogiri::HTML(File.open(filepath).read)

      events = element(doc, '#contenu div[id].vevent')
      events.each do |event|
        sessions << {
          year: 2008,
          title: title(event),
          description: description(event),
          authors: authors(event)
        }
      end
    end

    sessions += workshops

    sessions.reject do |session|
      session[:description].nil?
    end
  end

  def workshops
    doc = Nokogiri::HTML(File.open(@workshop_filepath).read)
    workshops = []

    events = element(doc, '.vevent')
    events.each do |event|
      title = clean_text(element(event, 'h3').text)
      next unless title =~ /^Paris/
      title = title.split(':')[1..-1].join(':').strip
      tags = element(event, '.sous-titre .summary').map(&:text)
      workshops << {
        year: 2008,
        type: 'workshop',
        title: title,
        tags: tags,
        description: description(event),
        authors: authors(event)
      }
    end

    workshops
  end

  def author_description(author)
    paras = element(author, '#orateur p')
    paras.each do |para|
      text = para.text.delete("\t").delete("\r").tr("\n", ' ').strip
      return text unless text.empty?
    end
    nil
  end

  def add_authors(sessions)
    authors = {}
    @authors_filepath.each do |filepath|
      doc = Nokogiri::HTML(File.open(filepath).read)

      name = element(doc, '#orateur h2').text
      picture = attribute(doc, '#orateur p.photo img', 'src')
      picture = "http://www.paris-web.fr/2008/#{picture}"
      description = author_description(doc)

      authors[name.slugify] = {
        name: name,
        picture: picture,
        description: description
      }
    end

    sessions = sessions.map do |session|
      session[:authors] = session[:authors].map do |author|
        matching_author = authors[author[:name].slugify]
        next if matching_author.nil?
        matching_author
      end
      session
    end

    sessions.reject(&:nil?)
  end

  def add_ressources(sessions)
    doc = Nokogiri::HTML(File.open(@ressources_filepath).read)
    ressources = {}

    lines = element(doc, 'tbody tr')
    lines.each do |line|
      element(line, 'td[rowspan="7"],td[rowspan="8"]').remove
      author_cell = element(line, 'td')[1]
      element(author_cell, 'small').remove
      slug = clean_text(author_cell.text).slugify

      slides = attribute(line, 'a[href$="pdf"]', 'href')
      next if slides.nil?

      video = attribute(line, 'a[href^="http://www.dailymotion"]', 'href')

      ressources[slug] = {
        slides: slides,
        video: video
      }
    end

    sessions.each do |session|
      next if session[:type] == 'workshop'
      slug = session[:authors].map do |author|
        author[:name]
      end.join('-').slugify

      slug = 'alix-lassaigne--christophe-cotin-valois' if slug == 'alix-lassaigne-christophe-cotin-valois'
      slug = 'stephane-deschamps--aurelien-levy' if slug == 'stephane-deschamps-aurelien-levy'

      session[:ressources] = ressources[slug]
    end

    sessions
  end

  def run
    content = add_authors(sessions)
    content = add_ressources(content)
    ap content

    output = HelperPath.record('2008')
    FileUtils.mkdir_p(File.dirname(output))
    content = JSON.pretty_generate(content)
    File.write(output, content)
  end
end

Selector2008.new.run
